version: '3.6'
services:
    postgres:
        container_name: db
        image: postgres:13-alpine
        environment:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_PORT
        ports:
        - 5432
        volumes:
        - ./postgresqldumps:/code/dumps
        - ./postgresql/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s
        
    web:
        container_name: test-web
        build: .
        command: sh -c "cd backend &&  python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn app.wsgi:application --bind 0.0.0.0:${BACKEND_PORT} --reload"
        volumes:
        - .:/code
        - ./static:/code/static
        - ./templates:/code/templates
        - ./media:/code/media
        expose:
        - 8000
        env_file:
        - .env
        restart: always
        depends_on:
            postgres:
                condition: service_healthy

    nginx:
        container_name: test-nginx
        build: ./nginx
        volumes:
        - ./static:/code/static
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
        - 81:80
        depends_on:
        - web

        