# Generated by Django 4.1.7 on 2023-03-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to='users.profile',
                        verbose_name='Author',
                    ),
                ),
            ],
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        )
    ]
